### ISSUE TITLE
test_evaluateMarkedCode : FAILED

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-devtools#186]
tests.html hasn't been kept up.  Try running `nwjs . --test`.

```
10:59:12.181  test_evaluateMarkedCode : FAILED (run individually)
10:59:12.182  ERROR in test_evaluateMarkedCode
WorkspaceFactoryGenerator is not defined
ReferenceError: WorkspaceFactoryGenerator is not defined
    at test_evaluateMarkedCode (file:///Users/marshalla/Projects/Blockly/devtools/tests/wfactory_input_test.js:86:19)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:899:21)
    at goog.testing.TestCase.safeRunTest_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.finishTestInvocation_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:999:10)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeTearDown_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:864:8)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeRunTest_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.finishTestInvocation_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:999:10)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeTearDown_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:864:8)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeRunTest_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.<anonymous> (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:790:12)
    at goog.testing.TestCase.invokeTestFunction_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runSetUpPage_ (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:803:8)
    at goog.testing.TestCase.<anonymous> (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:781:10)
    at new goog.Promise (file:///Users/marshalla/Projects/Blockly/devtools/lib/blockly_compressed.js:439:752)
    at goog.testing.TestCase.runTestsReturningPromise (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testcase.js:780:10)
    at goog.testing.TestRunner.execute (file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/testrunner.js:264:19)
    at file:///Users/marshalla/Projects/Blockly/devtools/closure-library/closure/goog/testing/jsunit.js:179:12
```

**Comment by chynu** [comment]
The test that failed is no longer relevant because importing toolboxes is done through a different function in a different class. In addition, the class and function this is referencing no longer exist in the post-refactored codebase. I suppose the better thing to do is just write another test function for importing files, but I am not entirely sure whether that is up on develop yet (there seems to be a PR in flight, #261).
